nodeLinker: node-modules

npmPublishRegistry: "https://registry-197565871292.d.codeartifact.us-east-1.amazonaws.com/npm/registry/"

npmScopes:
  classy:
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
    npmRegistryServer: "https://registry-197565871292.d.codeartifact.us-east-1.amazonaws.com/npm/registry/"

